run:
  allow-parallel-runners: true
linters:
  enable:
    - revive
  disable:
    - errcheck
linters-settings:
  unused:
    enabled: false
  revive:
    rules:
      - name: unused-parameter
        disabled: true